### ISSUE TITLE
Dispatcher doesn't cache anything

### ISSUE THREAD

**Issue by timdonovanuk** [aem-design/docker-dispatcher#6]
Using the latest dispatcher docker image with latest AEM docker image.

Here is my compose file:

```
  aem-publish-dispatcher:
    container_name: aem-publish-dispatcher
    image: aemdesign/dispatcher
    ports:
      - 8080:8080
      - 9433:8433
    volumes:
      - /opt/aem/dispatcher/cache:/data/httpd/cache
      - /opt/aem/dispatcher/logs:/data/httpd/logs
      - /opt/aem/dispatcher/redirectmap:/data/httpd/redirectmap
    environment:
      - "RENDERER_HOST=172.17.0.1"  
      - "RENDERER_PORT=4503"
      - "DISPATCHER_CONFIG=publish"
```
The dispatcher works (i.e. it passes through to publish successfully) but nothing ever actually gets cached, as evident by the empty /cache directory.
